export const COUNTRIES = [
  "Sri Lanka",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "India",
  "Malaysia",
  "Singapore",
  "Japan",
  "South Korea",
  "China",
  "Australia",
  "New Zealand",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Canada",
  "United States of America",
  "Russia",
  "Maldives",
  "Pakistan",
  "Bangladesh",
  "Thailand",
  "Indonesia",
  "Turkey",
  "Egypt",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Sweden",
  "Norway",
  "Netherlands",
  "Ireland",
  "Switzerland",
  "Spain",
  "Portugal",
  "Brazil",
  "Jordan",
  "Lebanon",
  "Iraq",
  "Yemen",
  "Libya",
  "Algeria",
  "Morocco",
  "Philippines",
  "Vietnam",
  "Myanmar",
  "Nepal",
  "Afghanistan",
  "Iran",
]

export const SRI_LANKA_CITIES: Record<string, string[]> = {
  "Ampara": [
    "Ampara",
    "Kalmunai",
    "Maruthamunai",
    "Sainthamaruthu",
    "Samanthurai",
    "Nintavur",
    "Akkaraipattu",
    "Addalaichenai",
    "Pottuvil",
    "Dehiattakandiya",
    "Uhana",
    "Padiyathalawa",
  ],
  "Batticaloa": [
    "Batticaloa",
    "Kattankudy",
    "Eravur",
    "Valaichchenai",
    "Kaluwanchikudy",
  ],
  "Colombo": [
    "Colombo",
    "Dehiwala",
    "Mount Lavinia",
    "Moratuwa",
    "Kotte",
    "Nugegoda",
    "Maharagama",
    "Piliyandala",
    "Kaduwela",
    "Malabe",
  ],
  "Gampaha": [
    "Gampaha",
    "Negombo",
    "Wattala",
    "Ja-Ela",
    "Kadawatha",
    "Minuwangoda",
    "Kelaniya",
  ],
  "Kandy": [
    "Kandy",
    "Peradeniya",
    "Katugastota",
    "Gampola",
    "Nawalapitiya",
  ],
  "Galle": [
    "Galle",
    "Hikkaduwa",
    "Ambalangoda",
    "Elpitiya",
    "Karapitiya",
    "Hapugala",
  ],
  "Matara": [
    "Matara",
    "Weligama",
    "Dikwella",
    "Deniyaya",
  ],
  "Jaffna": [
    "Jaffna",
    "Chavakachcheri",
    "Point Pedro",
    "Nallur",
  ],
  "Trincomalee": [
    "Trincomalee",
    "Kinniya",
    "Mutur",
    "Kantale",
  ],
  "Kurunegala": [
    "Kurunegala",
    "Kuliyapitiya",
    "Pannala",
    "Narammala",
  ],
  "Anuradhapura": [
    "Anuradhapura",
    "Kekirawa",
    "Medawachchiya",
    "Mihintale",
  ],
  "Badulla": [
    "Badulla",
    "Bandarawela",
    "Haputale",
    "Welimada",
  ],
  "Hambantota": [
    "Hambantota",
    "Tangalle",
    "Tissamaharama",
    "Beliatta",
  ],
  "Kalutara": [
    "Kalutara",
    "Panadura",
    "Beruwala",
    "Horana",
    "Bandaragama",
  ],
  "Kegalle": [
    "Kegalle",
    "Mawanella",
    "Rambukkana",
    "Warakapola",
  ],
  "Kilinochchi": [
    "Kilinochchi",
  ],
  "Mannar": [
    "Mannar",
  ],
  "Matale": [
    "Matale",
    "Dambulla",
    "Sigiriya",
    "Rattota",
  ],
  "Monaragala": [
    "Monaragala",
    "Wellawaya",
    "Bibile",
    "Buttala",
  ],
  "Mullaitivu": [
    "Mullaitivu",
  ],
  "Nuwara Eliya": [
    "Nuwara Eliya",
    "Hatton",
    "Nanu Oya",
    "Talawakelle",
  ],
  "Polonnaruwa": [
    "Polonnaruwa",
    "Kaduruwela",
    "Hingurakgoda",
  ],
  "Puttalam": [
    "Puttalam",
    "Chilaw",
    "Wennappuwa",
    "Marawila",
  ],
  "Ratnapura": [
    "Ratnapura",
    "Balangoda",
    "Embilipitiya",
    "Pelmadulla",
  ],
  "Vavuniya": [
    "Vavuniya",
  ],
}

// Flat list of all Sri Lankan cities for the city dropdown
export const SRI_LANKA_ALL_CITIES = Object.entries(SRI_LANKA_CITIES).flatMap(
  ([district, cities]) => cities.map(city => ({ city, district }))
)

// Popular cities outside Sri Lanka mapped by country
export const INTERNATIONAL_CITIES: Record<string, string[]> = {
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Fujairah", "Ras Al Khaimah"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Makkah", "Madinah", "Dammam", "Khobar"],
  "Qatar": ["Doha", "Al Wakrah", "Al Khor"],
  "Kuwait": ["Kuwait City", "Hawalli", "Salmiya"],
  "Bahrain": ["Manama", "Riffa", "Muharraq"],
  "Oman": ["Muscat", "Salalah", "Sohar"],
  "Malaysia": ["Kuala Lumpur", "Penang", "Johor Bahru", "Cyberjaya"],
  "Singapore": ["Singapore"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Leeds", "Edinburgh"],
  "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  "United States of America": ["New York", "Los Angeles", "Chicago", "Houston", "San Francisco"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "India": ["Chennai", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"],
  "Japan": ["Tokyo", "Osaka", "Nagoya"],
  "South Korea": ["Seoul", "Busan"],
  "Germany": ["Berlin", "Munich", "Frankfurt", "Hamburg"],
  "France": ["Paris", "Lyon", "Marseille"],
  "Italy": ["Rome", "Milan", "Naples"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch"],
  "Maldives": ["Malé"],
}
